version: '3.5'
services:
  voting:
    image: "yogeshraheja/thinknyxvote:v1"
    ports:
      - "81:80"
    networks: 
      - voting

  redis:
    image: "yogeshraheja/thinknyxredis:v1"
    networks: 
      - voting
      - db

  db:
    image: "yogeshraheja/thinknyxdb:v1"
    networks: 
      - db

  worker:
    image: "yogeshraheja/thinknyxworker:v1"
    networks: 
      - db
      - result

  result:
    image: "yogeshraheja/thinknyxresult:v1"
    ports:
      - "82:80"
    networks: 
      - result 
networks:
  voting:  
    name: voting
    driver: bridge 
  db: 
    name: db
    driver: bridge
  result: 
    name: result
    driver: bridge
